services:
  - type: web
    name: mia-telegram-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: <replace-with-telegram-token>
      - key: OPENAI_API_KEY
        value: <replace-with-openai-key>
      - key: ADMIN_USERS
        value: <comma-separated-telegram-ids>
      - key: ALLOWED_GROUPS
        value: ""
      - key: MODEL_NAME
        value: "gpt-4o-mini"
      - key: TEMPERATURE
        value: "1.0"
      - key: TOP_P
        value: "1.0"
      - key: MAX_TOKENS
        value: "250"
      - key: HISTORY_LENGTH
        value: "5"
      - key: MAX_MESSAGE_LENGTH
        value: "450"
      - key: SEND_USERNAME
        value: "true"
      - key: COOLDOWN_SECONDS
        value: "10"
